### PR TITLE
use pairwise from more_itertools

### PR DESCRIPTION
**Pull request by keisheiled**

### CODE REVIEW

**Comment by peterjc** [comment]
I don't know enough about mypy, but the linting failures on Python 3.8:

```
hookid: mypy

flake8_implicit_str_concat.py:16: error: No library stub file for module 'more_itertools'
flake8_implicit_str_concat.py:16: note: (Stub files are from https://github.com/python/typeshed)
flake8_implicit_str_concat.py:26: error: Generator has incompatible item type "Tuple[Any, ...]"; expected "Tuple[int, int, str, None]"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by keisheiled** [comment]
> I don't know enough about mypy, but the linting failures on Python 3.8:
> 
> ```
> hookid: mypy
> 
> flake8_implicit_str_concat.py:16: error: No library stub file for module 'more_itertools'
> flake8_implicit_str_concat.py:16: note: (Stub files are from https://github.com/python/typeshed)
> flake8_implicit_str_concat.py:26: error: Generator has incompatible item type "Tuple[Any, ...]"; expected "Tuple[int, int, str, None]"
> Found 2 errors in 1 file (checked 1 source file)
> ```

yeah sadly the pre-commit mypy doesn't have access to the tox environment, and therefore cannot "see" the requirements in the pyproject.toml

**Comment by hugovk** [comment]
Mypy can be kept in pre-commit by adding to `.pre-commit-config.yaml`:

```diff
     hooks:
       - id: mypy
         args: [--strict]
+        additional_dependencies: ["more_itertools"]
```

Docs: https://pre-commit.com

**Comment by keisheiled** [comment]
> 
> 
> Mypy can be kept in pre-commit by adding to `.pre-commit-config.yaml`:
> 
> ```diff
>      hooks:
>        - id: mypy
>          args: [--strict]
> +        additional_dependencies: ["more_itertools"]
> ```
> 
> Docs: [pre-commit.com](https://pre-commit.com)

but I don't want to duplicate the requirements from the `pyproject.toml`

**Pull request merged**
